# Generated by Django 4.2.7 on 2023-11-20 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_generatedimage_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='generated_image',
        ),
    ]
