# Generated by Django 4.2.7 on 2023-11-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_generatedimage_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='generated_image',
            field=models.ImageField(blank=True, null=True, upload_to='dalle-image'),
        ),
        migrations.DeleteModel(
            name='GeneratedImage',
        ),
    ]
