version: "3.8"

services:
  web:
    build: ./django
    command: python manage.py runserver 0:8000
    volumes:
      - .:/web
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    volumes:
      - ./docker/data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
