# Generated by Django 4.2.7 on 2023-11-25 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_generatedimage_post_author_post_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimage',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_images', to=settings.AUTH_USER_MODEL),
        ),
    ]
