# Generated by Django 4.2.7 on 2023-11-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='login_type',
            field=models.CharField(choices=[('normal', '일반'), ('kakao', '카카오')], default='normal', max_length=10, verbose_name='로그인 타입'),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='nickname'),
        ),
    ]
