# Generated by Django 4.2.7 on 2023-12-02 11:18

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=30, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('password', models.CharField(max_length=255, verbose_name='password')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='email')),
                ('profile_image', models.ImageField(blank=True, default='userProfile/default.png', null=True, upload_to='userProfile')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='phone_number')),
                ('nickname', models.CharField(blank=True, max_length=10, null=True, verbose_name='nickname')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='address')),
                ('zipcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='zipcode')),
                ('login_type', models.CharField(choices=[('normal', '일반'), ('kakao', '카카오')], default='normal', max_length=10, null=True, verbose_name='로그인 타입')),
                ('point', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('likes', 'likes'), ('comment', 'comment'), ('create', 'create')], default='likes', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('point', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
