# Generated by Django 4.2.7 on 2023-11-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_name_user_login_type_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_type',
            field=models.CharField(choices=[('normal', '일반'), ('kakao', '카카오')], default='normal', max_length=10, null=True, verbose_name='로그인 타입'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
