# Generated by Django 4.2.7 on 2023-12-01 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_login_type_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='point',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='userProfile/default.png', null=True, upload_to='userProfile'),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('likes', 'likes'), ('comment', 'comment'), ('create', 'create')], default='likes', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('point', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
